using System;
using System.Collections.Generic;

namespace Aire.Services
{
    public partial class OllamaService
    {
        public static readonly IReadOnlyDictionary<string, OllamaModelMeta> KnownModelMeta
            = BuildKnownModelMeta();

        private static Dictionary<string, OllamaModelMeta> BuildKnownModelMeta()
        {
            const long MB = 1_048_576L;
            const long GB = 1_073_741_824L;

            static OllamaModelMeta M(string[] tags, bool rec, string param = "", long size = 0) => new(tags, rec, param, size);

            return new Dictionary<string, OllamaModelMeta>(StringComparer.OrdinalIgnoreCase)
            {
                ["qwen3"] = M(["tools","thinking"], true, "8B", (long)(5.2*GB)),
                ["qwen3:0.6b"] = M(["tools","thinking"], false, "0.6B", (long)(0.5*GB)),
                ["qwen3:1.7b"] = M(["tools","thinking"], false, "1.7B", (long)(1.1*GB)),
                ["qwen3:4b"] = M(["tools","thinking"], true, "4B", (long)(2.6*GB)),
                ["qwen3:8b"] = M(["tools","thinking"], true, "8B", (long)(5.2*GB)),
                ["qwen3:14b"] = M(["tools","thinking"], true, "14B", (long)(9.0*GB)),
                ["qwen3:30b"] = M(["tools","thinking"], false, "30B", (long)(18.9*GB)),
                ["qwen3:32b"] = M(["tools","thinking"], true, "32B", (long)(20.5*GB)),
                ["qwen3:235b"] = M(["tools","thinking"], false, "235B", (long)(142.0*GB)),
                ["qwen2.5"] = M(["tools"], true, "7B", (long)(4.7*GB)),
                ["qwen2.5:7b"] = M(["tools"], true, "7B", (long)(4.7*GB)),
                ["qwen2.5:14b"] = M(["tools"], true, "14B", (long)(9.0*GB)),
                ["qwen2.5:32b"] = M(["tools"], false, "32B", (long)(20.0*GB)),
                ["qwen2.5:72b"] = M(["tools"], false, "72B", (long)(47.0*GB)),
                ["qwen2.5-coder"] = M(["tools","code"], true, "7B", (long)(4.7*GB)),
                ["qwen2.5-coder:7b"] = M(["tools","code"], true, "7B", (long)(4.7*GB)),
                ["qwen2.5-coder:14b"] = M(["tools","code"], false, "14B", (long)(9.0*GB)),
                ["qwen2.5-coder:32b"] = M(["tools","code"], false, "32B", (long)(20.0*GB)),
                ["ministral-3"] = M(["tools"], true, "8B", (long)(6.0*GB)),
                ["ministral-3:8b"] = M(["tools"], true, "8B", (long)(6.0*GB)),
                ["llama3.3"] = M(["tools"], true, "70B", (long)(43.0*GB)),
                ["llama3.3:70b"] = M(["tools"], true, "70B", (long)(43.0*GB)),
                ["llama3.2"] = M(["tools"], false, "3B", (long)(2.0*GB)),
                ["llama3.2:3b"] = M(["tools"], false, "3B", (long)(2.0*GB)),
                ["llama3.2:11b"] = M(["tools","vision"], true, "11B", (long)(7.9*GB)),
                ["llama3.1"] = M(["tools"], true, "8B", (long)(4.7*GB)),
                ["llama3.1:8b"] = M(["tools"], true, "8B", (long)(4.7*GB)),
                ["llama3.1:70b"] = M(["tools"], false, "70B", (long)(43.0*GB)),
                ["llama3.1:405b"] = M(["tools"], false, "405B", (long)(231.0*GB)),
                ["llama3"] = M([], false, "8B", (long)(4.7*GB)),
                ["llama3:8b"] = M([], false, "8B", (long)(4.7*GB)),
                ["llama3:70b"] = M([], false, "70B", (long)(40.0*GB)),
                ["mistral"] = M(["tools"], true, "7B", (long)(4.1*GB)),
                ["mistral:7b"] = M(["tools"], true, "7B", (long)(4.1*GB)),
                ["mistral-nemo"] = M(["tools"], true, "12B", (long)(7.1*GB)),
                ["mistral-small"] = M(["tools"], false, "22B", (long)(15.0*GB)),
                ["mistral-small3.1"] = M(["tools"], false, "24B", (long)(15.0*GB)),
                ["mixtral"] = M(["tools"], false, "8x7B", (long)(26.0*GB)),
                ["mixtral:8x7b"] = M(["tools"], false, "8x7B", (long)(26.0*GB)),
                ["mixtral:8x22b"] = M(["tools"], false, "8x22B", (long)(80.0*GB)),
                ["deepseek-r1"] = M(["thinking"], false, "7B", (long)(4.7*GB)),
                ["deepseek-r1:1.5b"] = M(["thinking"], false, "1.5B", (long)(1.1*GB)),
                ["deepseek-r1:7b"] = M(["thinking"], false, "7B", (long)(4.7*GB)),
                ["deepseek-r1:8b"] = M(["thinking"], true, "8B", (long)(5.0*GB)),
                ["deepseek-r1:14b"] = M(["thinking"], false, "14B", (long)(9.0*GB)),
                ["deepseek-r1:32b"] = M(["thinking"], false, "32B", (long)(20.0*GB)),
                ["deepseek-r1:70b"] = M(["thinking"], false, "70B", (long)(43.0*GB)),
                ["deepseek-r1:671b"] = M(["thinking"], false, "671B", (long)(404.0*GB)),
                ["deepseek-v3"] = M([], false, "671B", (long)(404.0*GB)),
                ["deepseek-v2.5"] = M([], false, "236B", (long)(133.0*GB)),
                ["deepseek-coder"] = M(["code"], false, "6.7B", (long)(3.8*GB)),
                ["deepseek-coder:6.7b"] = M(["code"], false, "6.7B", (long)(3.8*GB)),
                ["deepseek-coder:33b"] = M(["code"], false, "33B", (long)(19.0*GB)),
                ["gemma3"] = M(["tools","vision"], true, "4B", (long)(3.3*GB)),
                ["gemma3:1b"] = M(["tools","vision"], false, "1B", (long)(0.8*GB)),
                ["gemma3:4b"] = M(["tools","vision"], true, "4B", (long)(3.3*GB)),
                ["gemma3:12b"] = M(["tools","vision"], true, "12B", (long)(8.1*GB)),
                ["gemma3:27b"] = M(["tools","vision"], false, "27B", (long)(17.0*GB)),
                ["gemma2"] = M([], false, "9B", (long)(5.4*GB)),
                ["gemma2:9b"] = M([], false, "9B", (long)(5.4*GB)),
                ["gemma2:27b"] = M([], false, "27B", (long)(16.0*GB)),
                ["phi4"] = M(["tools"], true, "14B", (long)(9.1*GB)),
                ["phi4-mini"] = M(["tools"], true, "3.8B", (long)(3.8*GB)),
                ["phi4-reasoning"] = M(["thinking"], false, "14B", (long)(10.0*GB)),
                ["phi3"] = M([], false, "3.8B", (long)(2.2*GB)),
                ["phi3:3.8b"] = M([], false, "3.8B", (long)(2.2*GB)),
                ["phi3:14b"] = M([], false, "14B", (long)(7.9*GB)),
                ["granite4"] = M(["tools"], true, "3B", (long)(2.1*GB)),
                ["granite4:latest"] = M(["tools"], true, "3B", (long)(2.1*GB)),
                ["granite4:350m"] = M(["tools"], false, "350M", 708L * MB),
                ["granite4:1b"] = M(["tools"], false, "1B", (long)(3.3*GB)),
                ["granite4:3b"] = M(["tools"], true, "3B", (long)(2.1*GB)),
                ["granite3.3"] = M(["tools"], false, "8B", (long)(5.2*GB)),
                ["granite3.3:2b"] = M(["tools"], false, "2B", (long)(1.7*GB)),
                ["granite3.3:8b"] = M(["tools"], false, "8B", (long)(5.2*GB)),
                ["granite3.1-dense"] = M(["tools"], false, "8B", (long)(4.9*GB)),
                ["granite3.1-dense:2b"] = M(["tools"], false, "2B", (long)(1.6*GB)),
                ["granite3.1-dense:8b"] = M(["tools"], false, "8B", (long)(4.9*GB)),
                ["granite3.1-moe"] = M(["tools"], false, "3B", (long)(1.9*GB)),
                ["granite3-dense-128k"] = M(["tools"], false, "8B", (long)(5.0*GB)),
                ["codellama"] = M(["code"], false, "7B", (long)(3.8*GB)),
                ["codellama:7b"] = M(["code"], false, "7B", (long)(3.8*GB)),
                ["codellama:13b"] = M(["code"], false, "13B", (long)(7.4*GB)),
                ["codellama:34b"] = M(["code"], false, "34B", (long)(19.0*GB)),
                ["starcoder2"] = M(["code"], false, "7B", (long)(4.0*GB)),
                ["starcoder2:7b"] = M(["code"], false, "7B", (long)(4.0*GB)),
                ["starcoder2:15b"] = M(["code"], false, "15B", (long)(9.0*GB)),
                ["llava"] = M(["vision"], false, "7B", (long)(4.7*GB)),
                ["llava:7b"] = M(["vision"], false, "7B", (long)(4.7*GB)),
                ["llava:13b"] = M(["vision"], false, "13B", (long)(8.0*GB)),
                ["llava-llama3"] = M(["vision"], false, "8B", (long)(5.5*GB)),
                ["moondream"] = M(["vision"], false, "1.9B", (long)(1.7*GB)),
                ["nomic-embed-text"] = M(["embedding"], false, "137M", 274L * MB),
                ["mxbai-embed-large"] = M(["embedding"], false, "335M", 669L * MB),
                ["all-minilm"] = M(["embedding"], false, "23M", 46L * MB),
                ["solar"] = M([], false, "10.7B", (long)(6.1*GB)),
                ["solar-pro"] = M(["tools"], false, "22B", (long)(13.0*GB)),
                ["command-r"] = M(["tools"], false, "35B", (long)(20.0*GB)),
                ["command-r-plus"] = M(["tools"], false, "104B", (long)(59.0*GB)),
                ["orca-mini"] = M([], false, "3B", (long)(1.9*GB)),
                ["neural-chat"] = M([], false, "7B", (long)(4.1*GB)),
                ["vicuna"] = M([], false, "7B", (long)(3.8*GB)),
                ["openchat"] = M(["tools"], false, "7B", (long)(4.1*GB)),
                ["dolphin-mixtral"] = M(["tools"], false, "8x7B", (long)(26.0*GB)),
                ["dolphin-llama3"] = M(["tools"], false, "8B", (long)(4.8*GB)),
                ["yi"] = M([], false, "6B", (long)(3.5*GB)),
                ["yi:34b"] = M([], false, "34B", (long)(19.0*GB)),
                ["smollm2"] = M([], false, "1.7B", (long)(1.0*GB)),
                ["smollm2:1.7b"] = M([], false, "1.7B", (long)(1.0*GB)),
            };
        }
    }
}
